version: '3.7'
services:
#  redis:
#    container_name: redis
#    image: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - ../data/redis:/data
#    restart: always

  mafia-server:
    build:
      context: .
      dockerfile: mafia-server/Dockerfile
    image: mafia-server
    ports:
      - "8080"
    restart: always

  mafia-client:
    build:
      context: .
      dockerfile: mafia-client/Dockerfile
    image: mafia-client
    ports:
      - "3000"
    restart: always